"""partner table

Revision ID: df9b2a726f15
Revises: 26451b8f47a0
Create Date: 2026-10-03 03:23:56.536320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'df9b2a726f15'
down_revision: Union[str, Sequence[str], None] = '26451b8f47a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partners',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('zip_codes', sa.JSON(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('shipment', 'partner_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.drop_index(op.f('shipment_ibfk_2'), table_name='shipment')
    op.create_foreign_key(None, 'shipment', 'delivery_partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.create_index(op.f('shipment_ibfk_2'), 'shipment', ['partner_id'], unique=False)
    op.alter_column('shipment', 'partner_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_table('delivery_partners')
    # ### end Alembic commands ###
